# Intro to Numpy

In [2]:
import numpy as np

## Creating Arrays

In [3]:
# Create an array from a list

my_list = [1, 2, 3, 4, 5, 6]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5, 6])

In [4]:
# arrays have a shape: the number of elements along each axis
print(my_array.shape)

(6,)


In [5]:
# arrays have a dtype: the type of the elements in the array
print(my_array.dtype)

int64


In [6]:
# create arrays with zeros, ones, random numbers, etc.
zeros_array = np.zeros((2, 3))    # 2x3 array of zeros
ones_array = np.ones((3, 3))      # 3x3 array of ones
full_array = np.full((2, 2), 7)    # 2x2 array filled with 7
range_array = np.arange(0, 10, 2)  # array with values from 0 to 8 with a step of 2
linspace_array = np.linspace(0, 1, 5)  # array with 5 evenly spaced values between 0 and 1
random_array = np.random.rand(2, 3)  # 2x3 array with random values between 0 and 1


print("Array of zeros:\n", zeros_array)
print("Array of ones:\n", ones_array)
print("Array of sevens:\n", full_array)
print("Array of range:\n", range_array)
print("Array of linspace:\n", linspace_array)
print("Array of random numbers:\n", random_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array of sevens:
 [[7 7]
 [7 7]]
Array of range:
 [0 2 4 6 8]
Array of linspace:
 [0.   0.25 0.5  0.75 1.  ]
Array of random numbers:
 [[0.34406437 0.55599485 0.50421646]
 [0.00610254 0.39495572 0.0088718 ]]


## Common Operations

In [7]:
# perform operations on arrays

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Add two arrays
arr3 = arr1 + arr2
print("Add two arrays:\n", arr3)

# Subtract two arrays
arr4 = arr2 - arr1
print("Subtract two arrays:\n", arr4)

# Multiply two arrays
arr5 = arr1 * arr2
print("Multiply two arrays:\n", arr5)

# Divide two arrays
arr6 = arr2 / arr1
print("Divide two arrays:\n", arr6)

# Exponentiate two arrays
arr7 = arr1 ** arr2
print("Exponentiate two arrays:\n", arr7)

# Take the square root of an array
arr8 = np.sqrt(arr1)
print("Square root of an array:\n", arr8)

# Take the log of an array
arr9 = np.log(arr2)
print("Log of an array:\n", arr9)

# Take the sin of an array
arr10 = np.sin(arr1)
print("Sin of an array:\n", arr10)

Add two arrays:
 [ 7  9 11 13 15]
Subtract two arrays:
 [5 5 5 5 5]
Multiply two arrays:
 [ 6 14 24 36 50]
Divide two arrays:
 [6.         3.5        2.66666667 2.25       2.        ]
Exponentiate two arrays:
 [      1     128    6561  262144 9765625]
Square root of an array:
 [1.         1.41421356 1.73205081 2.         2.23606798]
Log of an array:
 [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
Sin of an array:
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


## Array Slicing

In [8]:
import numpy as np

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Slice elements from 1st to 4th position
print("Sliced Array:", arr1[1:4])

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr2)

# Slice a specific row
print("First row:\n", arr2[0])

# Slice a specific column
print("First column:\n", arr2[:, 0])

# Slice a submatrix
print("Submatrix:\n", arr2[0:2, 1:3])

1D Array: [1 2 3 4 5]
Sliced Array: [2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row:
 [1 2 3]
First column:
 [1 4 7]
Submatrix:
 [[2 3]
 [5 6]]


## Array Masking

In [9]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a mask
mask = arr > 5
print("Mask:", mask)

Mask: [False False False False False  True  True  True  True  True]


In [10]:
# Using the mask to index into the array
filtered_arr = arr[mask]
print("Filtered Array:", filtered_arr)

Filtered Array: [ 6  7  8  9 10]


## Exercise: The Alien Invasion

Original exercise can be found [here](https://matesanz.github.io/python-machine-learning-course/%F0%9F%A7%AA-Exercises/the-alien-invasion/).

In [11]:
import numpy as np


fleet_data = np.array([
    [120, 40, 25, 2.5, 10],
    [85, 60, 30, 5.0, 5],
    [100, 50, 35, 4.5, 7],
    [120, 40, 25, 2.5, 9],
    [150, 50, 30, 3.0, 10],
], dtype=np.float32)

In [12]:
# 1st exercise
total_spaceship = fleet_data.shape[0]
total_spaceship = len(fleet_data)
total_spaceship

5

In [13]:
# 2st exercise
length_column = fleet_data[:, 0]  # get first column and all rows
width_column = fleet_data[:, 1]  # get second column and all rows
height_column = fleet_data[:, 2]  # get third column and all rows

length_column, width_column, height_column

spaceship_volume = length_column * width_column * height_column
np.mean(spaceship_volume), spaceship_volume.mean()

(158600.0, 158600.0)

In [14]:
# 3rd exercise
speed_column = fleet_data[:, 3]
np.max(speed_column), np.min(speed_column), np.mean(speed_column)

(5.0, 2.5, 3.5)

In [15]:
# 4th exercise
MAX_POWER = 10


weapon_power_column = fleet_data[:, 4]
mask = weapon_power_column == MAX_POWER

# both are correct
np.count_nonzero(mask), len(weapon_power_column[mask])

(2, 2)

In [16]:
# 5th exercise
mask, speed_column
max_power_spaceships_speeds = speed_column[mask]
max_power_spaceships_speeds.mean()

2.75